[package]
name = "rix-tui"
version = "0.5.0"
edition = "2021"

[[bin]]
name = "rix-tui"
path = "src/main.rs"

[dependencies]
rix-core = { path = "../rix-core" }
rix-cli = { path = "../rix-cli" }

ratatui = { version = "0.28", features = ["serde"] }
crossterm = { version = "0.28", features = ["events"] }
tokio = { version = "1", features = ["full"] }
