use std::process::Command;
use std::fs;
use std::path::PathBuf;

#[derive(Debug)]
pub enum GpuVendor {
    Nvidia,
    Amd,
    Intel,
    Unknown(String),
}

impl GpuVendor {
    pub fn to_nixgl_wrapper(&self) -> &str {
        match self {
            GpuVendor::Nvidia => "nixGLNvidia",
            GpuVendor::Amd | GpuVendor::Intel => "nixGLIntel", // nixGLIntel handles both Mesa (AMD/Intel)
            GpuVendor::Unknown(_) => "nixGLDefault",
        }
    }
}

pub fn detect_primary_gpu() -> GpuVendor {
    let output = Command::new("lspci")
        .output()
        .expect("Failed to execute lspci. Is pciutils installed?");

    let output_str = String::from_utf8_lossy(&output.stdout).to_lowercase();

    // Look for lines containing VGA or 3D controller
    for line in output_str.lines() {
        if line.contains("vga") || line.contains("3d") || line.contains("display") {
            if line.contains("nvidia") {
                return GpuVendor::Nvidia;
            } else if line.contains("amd") || line.contains("radeon") {
                return GpuVendor::Amd;
            } else if line.contains("intel") {
                return GpuVendor::Intel;
            }
        }
    }

    GpuVendor::Unknown("fallback".to_string())
}

pub fn generate_hardware_lock(config_dir: &PathBuf) -> Result<(), std::io::Error> {
    let gpu = detect_primary_gpu();
    let wrapper = gpu.to_nixgl_wrapper();

    // We can expand this later, but here is our initial lock file!
    let lock_content = format!(
        "# AUTO-GENERATED BY RIX REFRESH - DO NOT EDIT MANUALLY\n\
        [hardware]\n\
        detected_gpu = \"{:?}\"\n\
        nixgl_wrapper = \"{}\"\n",
        gpu, wrapper
    );

    let lock_path = config_dir.join("hardware.lock");
    fs::write(&lock_path, lock_content)?;

    println!("✅ Hardware snapshot locked: Detected {:?} GPU. Assigning '{}'.", gpu, wrapper);
    println!("📄 Saved to: {}", lock_path.display());
    
    Ok(())
}

pub fn get_nixgl_wrapper(config_dir: &PathBuf) -> Option<String> {
    let lock_path = config_dir.join("hardware.lock");
    
    if let Ok(content) = fs::read_to_string(&lock_path) {
        for line in content.lines() {
            if line.starts_with("nixgl_wrapper") {
                let parts: Vec<&str> = line.split('=').collect();
                if parts.len() == 2 {
                    // Extract the value and strip the quotes/whitespace
                    let wrapper = parts[1].trim().trim_matches('"');
                    return Some(wrapper.to_string());
                }
            }
        }
    }
    
    // Return None if the file doesn't exist or parsing fails
    None
}
